/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface StcNested {}
  interface StcSimple {}
}

declare global {


  interface HTMLStcNestedElement extends Components.StcNested, HTMLStencilElement {}
  var HTMLStcNestedElement: {
    prototype: HTMLStcNestedElement;
    new (): HTMLStcNestedElement;
  };

  interface HTMLStcSimpleElement extends Components.StcSimple, HTMLStencilElement {}
  var HTMLStcSimpleElement: {
    prototype: HTMLStcSimpleElement;
    new (): HTMLStcSimpleElement;
  };
  interface HTMLElementTagNameMap {
    'stc-nested': HTMLStcNestedElement;
    'stc-simple': HTMLStcSimpleElement;
  }
}

declare namespace LocalJSX {
  interface StcNested {}
  interface StcSimple {}

  interface IntrinsicElements {
    'stc-nested': StcNested;
    'stc-simple': StcSimple;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'stc-nested': LocalJSX.StcNested & JSXBase.HTMLAttributes<HTMLStcNestedElement>;
      'stc-simple': LocalJSX.StcSimple & JSXBase.HTMLAttributes<HTMLStcSimpleElement>;
    }
  }
}


