/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {}
  interface MyNested {}
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLMyNestedElement extends Components.MyNested, HTMLStencilElement {}
  var HTMLMyNestedElement: {
    prototype: HTMLMyNestedElement;
    new (): HTMLMyNestedElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'my-nested': HTMLMyNestedElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent {}
  interface MyNested {}

  interface IntrinsicElements {
    'my-component': MyComponent;
    'my-nested': MyNested;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'my-nested': LocalJSX.MyNested & JSXBase.HTMLAttributes<HTMLMyNestedElement>;
    }
  }
}


